---
title: "Timeline of Metrorail stations opening"
author: "KHYS / kshu"
date: "25 August 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# require(knitr)
library(shiny)
library(leaflet)
# library(htmlwidgets)

source("compile_wmata_stations.R")
dfFull<-lstRes$concise
lstLines<-lstRes$lines
superBounds<-function(x)  {
  ORDERS_MAG<-2
  stopifnot(ORDERS_MAG %% 1 == 0)
  res<-c((floor(10^ORDERS_MAG * min(x))-1)/10^ORDERS_MAG,
         (ceiling(10^ORDERS_MAG * max(x))+1)/10^ORDERS_MAG)
  return(res)
}
```

```{r timeline, echo=FALSE}
sliderInput("histDate", "Date",
            min(dfFull$Opened), max(dfFull$Opened),
            value = as.Date("1976-12-31"), step = 1)

renderLeaflet({
  filteredData <- reactive({
    list(concise=dfFull %>% filter(Opened <= input$histDate),
         lines=lapply(lstLines, function(df) df %>%
                        filter(Opened <= input$histDate)))
  })
  
  nominalDim<-c(512,655)
  nominalFactor<-nominalDim[1]/nominalDim[2]
  ht<-10
  metrorailIcon <- makeIcon(
    iconUrl = "https://upload.wikimedia.org/wikipedia/commons/1/1e/WMATA_Metro_Logo.svg",
    iconWidth = ht*nominalFactor, iconHeight = ht,
    iconAnchorX = ht*nominalFactor/2, iconAnchorY = 16
  )
  
  dataSubset<-filteredData()
  dfSubset<-dataSubset$concise
  lstPartialLines<-dataSubset$lines
  
  thisMap<-leaflet(dfSubset) %>%
    addTiles() %>%
    fitBounds(superBounds(dfFull$Lon)[1], superBounds(dfFull$Lat)[1],
              superBounds(dfFull$Lon)[2], superBounds(dfFull$Lat)[2]) %>%
    clearMarkers() %>%
    clearShapes() %>%
    addMarkers(lat = dfSubset$Lat,
               lng = dfSubset$Lon,
               # popup=dfSubset$Name,
               popup=paste("Name: ", dfSubset$Name, "<br/>",
                           "Opened: ", dfSubset$Opened, "<br/>",
                           "Serves: <br/>", dfSubset$Lines,
                           "<br/> Coordinates: (", dfSubset$Lat,
                           ", ", dfSubset$Lon, ")", 
                           sep=""),
               #     "Opened date: "),
               icon=metrorailIcon) %>%
    addPolylines(lng=lstPartialLines$rd$Lon,
                 lat=lstPartialLines$rd$Lat,
                 color = "Red") %>%
    addPolylines(lng=lstPartialLines$or$Lon,
                 lat=lstPartialLines$or$Lat,
                 color = "Orange") %>%
    addPolylines(lng=lstPartialLines$sv$Lon,
                 lat=lstPartialLines$sv$Lat,
                 color = "Silver", opacity=1) %>%
    addPolylines(lng=lstPartialLines$yl$Lon,
                 lat=lstPartialLines$yl$Lat,
                 color = "Yellow") %>%
    addPolylines(lng=lstPartialLines$bl$Lon,
                 lat=lstPartialLines$bl$Lat,
                 color = "Blue", opacity=0.3) %>%
    addPolylines(lng=lstPartialLines$gr$Lon,
                 lat=lstPartialLines$gr$Lat,
                 color = "Green")
  # saveWidget(thisMap, file="Metrorail_stations_timeline.html")
}
)
```